### ISSUE TITLE
Stuck buttons

### ISSUE THREAD

**Issue by spotUP** [va7deo/SNK68#1]
Hello, i just tested my player 1 rotary after having soldered the wires.
I tried it in windows in notepad.
If i rotate in any direction the buttons gets stuck as if they are held down?
It looks something like this:
aaaaaaaaabbbbbbbcccccccccccddddddddddddd

what could be wrong?

**Comment by spotUP** [comment]
Video for reference:
https://youtu.be/7HNYnXcWogk

**Comment by atrac17** [comment]
This has been addressed in multiple places. You need to use the core that the LS-30 is intended for. It's functional.

**Comment by spotUP** [comment]
I haven’t tried any core yet and thought that key repeat wasn’t normal, but i it got confirmed that is is, so all good there.Both my sticks are wired up and working now, but all push buttoms seems dead. Gonna check them with a multimeter soon.Thanks for the reply!Have a good day!//johanSkickat från min iPhone28 sep. 2022 kl. 15:42 skrev atrac17 ***@***.***>:﻿
This has been addressed in multiple places. You need to use the core that the LS-30 is intended for. It's functional.
