### ISSUE TITLE
P.O.W - Black "square" rightmost side of the screen

### ISSUE THREAD

**Issue by Toryalai1** [va7deo/SNK68#3]
There seems to be a black square on the rightmost side of the screen. It's not there at the beginning of the game but 5 minutes into the game. See attached screenshot
![20221020_115755-screen](https://user-images.githubusercontent.com/82502378/196929748-b41fcd3e-0848-4d31-aebf-36f4b7056c15.png)

Thank you for the hard work on the core

**Comment by va7deo** [comment]
Thanks for reporting this.

**Comment by atrac17** [comment]
Which ROM set? Thought this was fixed. Thanks.

**Comment by Toryalai1** [comment]
I tried with the previous build and it doesn't happen there. Then I tried again with the latest build and I couldn't reproduce it. I will close this issue
