### ISSUE TITLE
Rotarys acting weird

### ISSUE THREAD

**Issue by spotUP** [va7deo/SNK68#4]
Hi! I built your adaptor, the push buttons are fine, but the rotarys register very weirdly. When rotating to the left a lot of clicks are missed and sometimes the character that should be outputed when rotating the other direction gets printed instead. Same when rotating right. 

Here's a video of me first rotating left, then right followed by left/right quickly.
https://www.youtube.com/watch?v=MQB0JC1gsnQ

Any idea how it could be adjusted?

**Comment by spotUP** [comment]
It was incorrect wiring! Working good now! 
any chanse of adding support to the heavy barrel core?

**Comment by atrac17** [comment]
No issue, user improperly wired. Once I refactor everything and move to a two button setup the code will be available for any core author to take and use.
